# Generated by Django 2.2.13 on 2020-11-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='result',
        ),
        migrations.AddField(
            model_name='score',
            name='msg',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='ph',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
